### ISSUE TITLE
pos.clone() is not defined

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/shogiops#3]
I'm attempting to make a Discord bot which displays a player's recent games, with a human-readable move list.  But I see in `shogi.js` that `clone()` is defined, so I must be making a coding error somehow:
![image](https://user-images.githubusercontent.com/1834123/178446774-9f5c07f7-d8f1-431d-945a-48531c2e65bb.png)

https://github.com/ddugovic/lishogi-discord/blob/2ca5f2519bb535f78fdad6e39bf1b2a587540e48/lib/format-variation.js#L1-L34

https://github.com/WandererXII/shogiops/blob/c3d642452fb078d66b6c2ab01ddeadf246376fde/src/notation/csa/csa.ts#L191-L201

**Comment by WandererXII** [comment]
`parseSfen` returns `Result<Position, SfenError>;` from [badrap](https://github.com/badrap/result).
So you need to call unwrap(), if you just want to ignore possible failure to parse the sfen;

Something like this:
```javascript
async function setup(fen) {
    const { initialSfen, parseSfen } = await sfen;
    return parseSfen('standard', fen ?? initialSfen('standard'), false).unwrap();
}
```

Also `ParseCsaMoves` parses only csa moves - https://github.com/WandererXII/shogiops/blob/master/test/notation/csa.test.ts. Not the pgn I see on the picture. In the next lishogi update (currently finalizing) all san/pgn will be removed. So the endpoints that up until now returns pgn/san will return usi.

**Comment by ddugovic** [comment]
Thanks for your great explanation & help!
![image](https://user-images.githubusercontent.com/1834123/185022834-9f6da2db-be53-487d-b229-7803c234d9b2.png)
