### ISSUE TITLE
Chu shogi notation

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/shogiops#5]
It wasn't clear to me how to translate a USI move list from https://lishogi.org/api#tag/Games/operation/apiUserCurrentGame into western or other notations.
https://github.com/ddugovic/lishogi-discord/commit/18ff16b2399995ed42407a06fef7abf91a6f961f

**Comment by WandererXII** [comment]
Sorry for the late reply. It should work the same for all variants. I think the issue might in `setup`, you should use the current variant in `parseSfen`. Something like this:

```javascript
async function setup(variant, sfen) {
    const { initialSfen, parseSfen } = await sfen;
    return parseSfen(variant, sfen ?? initialSfen(variant), false).unwrap();
}
```

**Comment by ddugovic** [comment]
Perfect!  No worries, thanks for correcting my obvious-in-hindsight error!
